// Code generated by DevUp technologies, 02/08/2024 14:36:00
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementDAL
{
    public class InventoryManagementContext : DbContext
    {
        public InventoryManagementContext(DbContextOptions<InventoryManagementContext> options) : base(options)
        {
        }


		public DbSet<Product> Product { get; set; }


    }
}

