// Code generated by DevUp technologies, 02/08/2024 14:36:00
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementDAL.Container
{
    public class IOCContainer
    {
        private static IOCContainer _instance;
        private string ConnectionString { get; set; }
        public static void Initialize(string connectionString)
        {
            IOCContainer.Instance.ConnectionString = connectionString;
        }
        public static IOCContainer Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new IOCContainer();

                return _instance;
            }
        }

        public DbContextOptionsBuilder<InventoryManagementContext> OptionsBuilder
        {
            get
            {
                var optionsBuilder = new DbContextOptionsBuilder<InventoryManagementContext>();
                return optionsBuilder.UseSqlServer(ConnectionString);
            }
        }

        public InventoryManagementContext Context
        {
            get
            {
                return new InventoryManagementContext(IOCContainer.Instance.OptionsBuilder.Options);
            }
        }
		public ProductRepository ProductRepository
		{
			get
			{
				return new ProductRepository(Context);
			}
		}


    }
}

