// Code generated by DevUp technologies, 02/08/2024 14:36:01
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.OpenApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InventoryManagementWApi.Extensions;
using InventoryManagementWApi.HealthChecks;
using InventoryManagementDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace InventoryManagementWApi
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddCors(options =>
            {
                options.AddPolicy("AllowOrigin",
                    builder =>
                    {
                        builder.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader();
                    });
            });

            services.AddControllers();

            services.AddControllers().AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.PropertyNamingPolicy = null;
            });
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "InventoryManagementWApi", Version = "v1" });
            });

            

            string connectionStringAutoConfig = Configuration.GetConnectionString("DbEntities");
            			//db migration
				InventoryManagementDAL.Container.IOCContainer.Initialize(connectionStringAutoConfig);
				services.AddDbContext<InventoryManagementContext>(x => x.UseSqlServer(connectionStringAutoConfig));


            
            services.AddHealthChecks().AddCheck<SystemConfigHealthCheck>("SystemConfigurations");
            services.AddHealthChecks().AddCheck("CheckDbConnecivity", new DbServerHealthCheck(connectionStringAutoConfig));

            services.AddServices();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IServiceProvider serviceProvider)
        {
            app.UseCors(options =>
            {
                options.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader();
            });

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "InventoryManagementWApi v1"));
            }

            //app.UseHttpsRedirection();

            app.UseRouting();
            app.ConfigureServices(env);
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseCors(options =>
            {
                options.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader();
            });
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            			serviceProvider.GetService<InventoryManagementContext>().Database.GetService<IMigrator>()
				.Migrate(Configuration.GetValue<string>("Migration"));


        }
    }
}

