// Code generated by DevUp technologies, 02/08/2024 14:36:01
using AutoMapper;
using CommonInterfaces;
using InventoryManagementDAL;

namespace CommonServices.Mappers
{
    public class DTOToEFProfile : Profile
    {
        public DTOToEFProfile()
        {
            
			CreateMap<ProductDTO, Product>();
			CreateMap<ProductFilterDTO, ProductFilter>();

 
        }
    }
}
