// Code generated by DevUp technologies, 02/08/2024 14:36:01
using AutoMapper;
using CommonInterfaces;
using InventoryManagementDAL;

namespace CommonServices.Mappers
{
    public class EFToDTOProfile : Profile
    {
        public EFToDTOProfile()
        {
			
			CreateMap<Product, ProductDTO>();
			CreateMap<ProductFilter, ProductFilterDTO>();

 
        }
    }
}

