// Code generated by DevUp technologies, 02/08/2024 14:36:01
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CommonInterfaces
{
	/// <summary>
    /// This interface contains all methods that service layer is exposing the top level layers like API controller
    /// This interface is implemented in CommonServices project and is used/refferd by API layer
    /// API layer is registering this interface as service at startup and then its injected by framework to 
    /// controller classes via constrctors
    /// </summary>
	public interface IProductService
    {
        Task<List<ProductDTO>> GetAll();
		Task<int> GetTotal();
        Task<List<ProductDTO>> GetByFilter(ProductFilterDTO dataFilter);		
		Task<int> GetByFilterTotal(ProductFilterDTO dataFilter);
        Task<ProductDTO> GetById(long id);
		Task<bool> Create(ProductDTO dataItem);
		Task<long> CreateGetId(ProductDTO dataItem);
		Task<bool> Update(ProductDTO dataItem);
		Task<bool> DeleteById(long id);
		

    }
}
