// Code generated by DevUp technologies, 02/08/2024 14:36:00
using System;
using System.ComponentModel.DataAnnotations;

namespace CommonInterfaces
{
	/// <summary>
    /// This class contain DTO, A plain data object to carry data, It does not contain any business logic or validations, 
	/// and is used to transfer filter data in optimized format between API and client or layer that will be using it.
	/// this DTO object carries data from client to service layer and vice versa, at service layer it is mapped to its equivalent 
	/// entity object and sent to data access layer
    /// </summary>
    public class ProductDTO
    {
		public System.Int64 Id { get; set; }
		public System.DateTime ProductionDate { get; set; }
		public System.String Name { get; set; }
		public System.Decimal NetPrice { get; set; }
		public System.Decimal SalesPrice { get; set; }
		public System.Double StockQuantity { get; set; }
		public Nullable<System.Int32> CategoryId { get; set; }
		public Nullable<System.Int32> Status { get; set; }

    }
}

