// Code generated by DevUp technologies, 02/08/2024 14:36:01
using CommonInterfaces;
using CommonServices;

namespace InventoryManagementWApi.Extensions
{
    public static class ServiceRegistration
    {
        public static void AddServices(this IServiceCollection services)
        {
			services.AddScoped<IProductService, ProductService>();


        }
    }
}

