// Code generated by DevUp technologies, 02/08/2024 14:36:01
using InventoryManagementWApi.Middleware;

namespace InventoryManagementWApi.Extensions
{
    public static class ServiceExtensions
    {
        public static IApplicationBuilder ConfigureServices(this IApplicationBuilder app, 
            IWebHostEnvironment env)
        {
            app.UseHealthChecks("/health");
            return app.UseMiddleware<InvokeActionMiddleware>();
        }
    }
}

